### ISSUE TITLE
Cannot build njs binary for Windows

### ISSUE THREAD

**Issue by shikhar022** [jirutka/nginx-binaries#5]
@jirutka I could not find njs binaries for Windows on https://jirutka.github.io/nginx-binaries/  

Am I missing something here? Or you are yet to add support for Windows njs binaries?

**Comment by jirutka** [comment]
njs doesn’t support Windows, only unix systems.

**Comment by shikhar022** [comment]
Thanks for the information. So that means on Windows system this won't work. I will HAVE to go the docker way.

**Comment by jirutka** [comment]
> I will HAVE to go the docker way.

No, you don’t have to go the docker way, you can simply use WSL (Windows Subsystem for Linux).

**Comment by shikhar022** [comment]
But thats not sustainable on IIS server right? We need an end-to-end CI/CD setup for this.
